FROM selenium/standalone-chrome
MAINTAINER Aditya Inapurapu adityaii@gmail.com
RUN sudo mkdir -p /usr/src/app
RUN sudo apt-get update -y && sudo apt-get install -y maven
RUN sudo wget https://download.java.net/openjdk/jdk11/ri/openjdk-11+28_linux-x64_bin.tar.gz -O /tmp/openjdk-11+28_linux-x64_bin.tar.gz  -O /tmp/openjdk-11+28_linux-x64_bin.tar.gz
RUN sudo tar xfz /tmp/openjdk-11+28_linux-x64_bin.tar.gz --directory /usr/lib/jvm
RUN sudo rm -rf /usr/bin/java && sudo ln -s /usr/lib/jvm/jdk-11/bin/java /usr/bin/java
RUN sudo rm -f /tmp/openjdk-11+28_linux-x64_bin.tar.gz
WORKDIR /usr/src/app
ADD . /usr/src/app
RUN java -version
RUN sudo mvn clean test
