FROM selenium/standalone-chrome
MAINTAINER Aditya Inapurapu adityaii@gmail.com
RUN sudo mkdir -p /usr/src/app
RUN sudo apt-get update -y && sudo apt-get install -y maven default-jdk
WORKDIR /usr/src/app
ADD . /usr/src/app
RUN java -version
RUN sudo mvn clean test
